// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export * from "./awsinstance";
export * from "./azureInstance";
export * from "./gcpinstance";
export * from "./provider";

// Import resources to register:
import { AWSInstance } from "./awsinstance";
import { AzureInstance } from "./azureInstance";
import { GCPInstance } from "./gcpinstance";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "run-my-darn-container:index:AWSInstance":
                return new AWSInstance(name, <any>undefined, { urn })
            case "run-my-darn-container:index:AzureInstance":
                return new AzureInstance(name, <any>undefined, { urn })
            case "run-my-darn-container:index:GCPInstance":
                return new GCPInstance(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("run-my-darn-container", "index", _module)

import { Provider } from "./provider";

pulumi.runtime.registerResourcePackage("run-my-darn-container", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:run-my-darn-container") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
